### ISSUE TITLE
Weird character on the log

### ISSUE THREAD

**Issue by MrAmericanMike** [sindresorhus/electron-timber#20]
Sorry not sure if this is an actual problem, or just something missing some configuration on my end, or ConEmu making things not work...

On my console I see the outputs like:
main ÔÇ║ ####################
main ÔÇ║ #### NEW START #####
main ÔÇ║ ###################

Meaning that I get ÔÇ║ instead of the >

Also the output is not in colors.

What could be causing this problems?
Thanks in advance for the support.

**Comment by sindresorhus** [comment]
Your terminal doesn't support unicode characters.

**Comment by MrAmericanMike** [comment]
Ohh ok. Thanks for the heads-up. Gonna see into changing to a different once. Thanks for the answer.

**Comment by catdad** [comment]
I know this is an old issue, but it seems that it is not simply an issue of the terminal. On Windows, I can put the following code in a file and run it through node directly:

```javascript
console.log(require('chalk').red('›'))
```

I get it to print correctly. The character prints, and so does the color:

![image](https://user-images.githubusercontent.com/2205537/53779848-c7a2d300-3ecf-11e9-8255-461febae147e.png)

However, when I require that same file within the main process of my electron app, again using Electron on Windows, I get this:

![image](https://user-images.githubusercontent.com/2205537/53779889-f4ef8100-3ecf-11e9-9494-737c4f7b9879.png)

And, of course, when I force color, I get colors but the character still looks odd:

![image](https://user-images.githubusercontent.com/2205537/53779930-22d4c580-3ed0-11e9-996a-e45753b56a59.png)

It seems like this is not an issue with the terminal, but rather with something in Electron. Though, it is worth noting that when I change `›` to the ascii `>`, it prints fine:

![image](https://user-images.githubusercontent.com/2205537/53779972-4d268300-3ed0-11e9-88aa-99628f10f0e4.png)

There might be something to considering using a different character, even if it is just for Windows

**Comment by MrAmericanMike** [comment]
I was also testing electron-log with similar issues, it works when I run the .js as node but when I run it as electron again the weird characters show up. So I assume the console I'm using supports the colors, but for some reason something in electron is making this modules behave in a weird way?

![logs](https://i.imgur.com/LkWJzsD.png)
