### ISSUE TITLE
Logging an error is correct in the Electron devtools console, but an empty object {} in the terminal output

### ISSUE THREAD

**Issue by lacymorrow** [sindresorhus/electron-timber#22]
```js
	import { shell } from 'electron'

	try {

		await shell.openExternal( resource )

	} catch ( error ) {

		 // displays `{}` in the terminal
		logger.log( error )

		 // prints the strings in the terminal
		logger.log( error.message, error.stack )

	}
```

This seems to be related: https://stackoverflow.com/a/38513494/939330

**Comment by sindresorhus** [comment]
What Electron version? I think Electron 8 finally fixed the bug where it doesn’t correctly serialize errors.

**Comment by lacymorrow** [comment]
That could be why, I'm still using Electron 6 because of this bug: https://github.com/electron/electron/issues/20933.

Cheers!
