### ISSUE TITLE
Add `logLevel` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-timber#6]
I'm thinking it might be useful to have a `logLevel` option, so you could choose what level to log based on the environment. I think a good default would be to set it to `log` (info) in development and `warn` in production, so it doesn't output `log` messages in production.

There should also be a way to set it for all logger instances, maybe:

```js
const logger = require('timber');

logger.setDefaults({
	logLevel: 'warn'
});
```

@acheronfail @lukechilds Thoughts?

**Comment by acheronfail** [comment]
Would this be implemented as a "whole app" configuration or per process?

ie: should calling `logger.setDefaults()` in main only change the main process' log levels, or should it configure both processes' loggers?

**Comment by sindresorhus** [comment]
The `.setDefaults()` would apply to all instances (`renderer`/`main`/`custom`), but you could override it in your custom logger `timber.create({logLevel: 'warn'})`. It should not be possible to set it differently for main and renderer though.

**Comment by acheronfail** [comment]
How would we keep the defaults synced between processes? 

I think we'd probably have to keep an object in the `main` process, and request that object whenever a new `renderer` process is created. Otherwise the defaults may get out of sync when new instances are initialised in new windows.

**Comment by lukechilds** [comment]
>I think a good default would be to set it to log (info) in development and warn in production, so it doesn't output log messages in production.

Makes sense. What are the downsides of log over warn in production btw? Just cleanliness?

**Comment by sindresorhus** [comment]
> I think we'd probably have to keep an object in the main process, and request that object whenever a new renderer process is created. Otherwise the defaults may get out of sync when new instances are initialised in new windows.

Yes, or just sync the default to both process whenever the user does `setDefaults()`.

Or we could just support `setDefaults()` in the main process. That would be much simpler actually. I don't really see the point in being able to set it in renderer processes.

**Comment by sindresorhus** [comment]
> What are the downsides of log over warn in production btw? Just cleanliness?

Cleanliness and to not log potentially sensitive info.

**Comment by acheronfail** [comment]
> Or we could just support `setDefaults()` in the main process. 

Each renderer process will still have to request the defaults on initialisation though. If the user calls `setDefaults()` and then some time later creates another renderer process then the new renderer will need to fetch the defaults (since it didn’t exist when `setDefaults()` was originally called)

**Comment by sindresorhus** [comment]
@acheronfail We can just expose the defaults as a global, see: https://electronjs.org/docs/api/remote#remotegetglobalname

**Comment by acheronfail** [comment]
🤦‍♂️ Ahh, I can't believe I didn't think of that - I've even used it before.

I'll see if I can draft a PR sometime soon 😄
