### ISSUE TITLE
Opt-in way to hook `console` methods

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-timber#9]
Some people may want to direct all logging to `electron-timber`, even logging they don't control. The only solution then is to hook the `console.*` methods. I think we should provide a way to easily do that.

Something like this:

```js
logger.setDefaults({hookConsole: true});
```

And you can then use `console.log` in the renderer and have it appear in the terminal.

@acheronfail Thoughts?

**Comment by acheronfail** [comment]
Seems like a decent idea, would mean that people could adopt `electron-timber` without it affecting much of their codebase at all - I like it. 👍

Although, what should the behaviour be if the user executes this?

```js
const logger = require('electron-timber');
logger.setDefaults({hookConsole: true});

const custom = logger.create({hookConsole: true});

console.log('foobar'); // which should take precedence?
```

Maybe it should just overwrite - as in, the last logger that was created with `hookConsole: true` should be the one that hooks the console.

**Comment by sindresorhus** [comment]
Maybe we should not have it as an option then?

```js
logger.hookConsole();
```

Then you can only hook `console` with the default logger in main and renderer.

**Comment by acheronfail** [comment]
> Maybe we should not have it as an option then?

Yeah, I think if we only provide `hookConsole()` on the default logger (not on custom loggers) that could work. 

I’ll draft up a PR and we can see if that’s the direction we should go.
